### ISSUE TITLE
Unable to list remote backups

### ISSUE THREAD

**Issue by robinvdvleuten** [timmyomahony/craft-remote-core#22] opened 2023-11-21 13:07 UTC
I am currently receiving an error when trying to view the remote backups overview.

![image](https://github.com/timmyomahony/craft-remote-core/assets/238295/407a6890-07b0-46bc-9d68-806716e63f56)

When inspecting the error logs of Craft, I see the following error.

```
[object] (Error(code: 0): Call to a member function setTimezone() on bool at ***/vendor/weareferal/remote-core/src/helpers/RemoteFile.php:51 
```

It seems that somehow the `DateTime::createFromFormat` is returning `false` here and thus the next call that sets the timezone fails (https://github.com/timmyomahony/craft-remote-core/blob/main/src/helpers/RemoteFile.php#L47-L51)

I am using Backblaze as remote storage provider.

**Comment by robinvdvleuten** [comment] 2023-11-21 13:18
After investigating further, it could be caused by the site name containing a dot and not matching one of the regexes?

**Comment by timmyomahony** [comment] 2023-11-21 13:23
Hi Robin, yes I think that is the cause. The plug-in uses a regex to pull information from the file names. I think this is causing the error. 

I have a fix for this but haven’t released yet. I’ll see if I can get that out but if you can change the site name easily than that will fix the issue 

- Timmy

**Comment by robinvdvleuten** [comment] 2023-11-26 09:51
I fixed it for now by forking this package and changing the regular expression myself.

**Comment by timmyomahony** [comment] 2023-12-07 23:33
Hi @robinvdvleuten I'm hoping this should be fixed in the latest version `remote-backup` which is `4.1.6`. I've simplified the regex so it should be more permissive.

Try it out and let me know how you get on. Any problems and I'll reopen the issue.

**Closed by timmyomahony** 2023-12-07 23:33 UTC
